public class ApexVariables {
    
    //Class will have methods
    //class will have variables
    //Three kinds of variables 
    //1. Instance variables
    //2. Local variables
    //3. Static Variables
    
    // Variables are used to store data of specific type of data 
    
    // Data types :- Data type specifically specifies a type of data being stored
    // 1. primitive data type
    // 2. Non primitive data types
    // ** primitive data types
  
    // decimal
    // integer
    // string 
    // boolean (true / false )
    
    // Non -primitive data types (collections)
    // 1. List
    // 2.Set
    // 3.Map
    // 
    //  Sobject (salesforce object)
    
    // A variables is a memory location which is capable of storing the data of a particular data type
    // A variable is a memory location which is capable of pointing to a specific location of its own data type    
}