public class ApexIntro1  //ApexIntro1 is the class name 

 // this is used to comment one line
 /* This is 
  * used to comment 
  * multiple 
  * lines */

// Apex is a Non case sensitive lang 
// every class comprises of methods and Variables
// class will have business functionalities ,methods ,which are helpfull in achieving our requirements ...
// So now run and execute the program (to create the [instance of an program ] )
// Keywords : these are the words with specific meaning , whose meaning doesnt change 
// To create an instance , we will use a [Keyword : NEW]
{

    public void method1()
    {
        
    }
    
    public void method2()
    {
        
    }
}